SETTINGS:
  SERVER:
    SEND-WELCOME-MESSAGE: true
    ALLOW-WEATHER-CHANGE: false
    ALLOW-THUNDERS-SPAWN: false
    ALLOW-MOBS-SPAWN: false
    ALLOW-ANIMALS-SPAWN: false
    TIMELOCK-ENABLED: true
    TIMELOCK: 12000 # This goes as ticks, 6000 = DAY, 12000 = SUNSET, 18000 = NIGHT
    TABLIST: true
  PLAYER:
    ALLOW-OP-PLAYERS-BYPASS: false
    ALLOW-BLOCK-BREAK: false
    ALLOW-BLOCK-PLACE: false
    ALLOW-ITEM-DROP: false
    ALLOW-ITEM-PICKUP: false
    ALLOW-HUNGER: false
    ALLOW-DAMAGE: false
    INFINITE-DOUBLE-JUMP: true
